# Generated by Django 5.1.1 on 2024-09-10 03:43

import django.db.models.deletion
import helpers.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('email', models.CharField(blank=True, db_index=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'abstract': False,
            },
        ),
    ]
