# Generated by Django 5.1 on 2024-09-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_profile_asset_profile_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='asset',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
